# Generated by Django 5.1.5 on 2025-02-04 15:10

import Gestion.Validadores
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=50, verbose_name='Cambio'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='cargo',
            field=models.CharField(choices=[('1', 'Gerente'), ('2', 'Vendedor'), ('3', 'Cajero')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='id',
            field=models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), Gestion.Validadores.validacion_numeros]),
        ),
    ]
