# Generated by Django 5.1.5 on 2025-02-10 22:12

import Gestion.Validadores
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_categoria_alter_empleado_apellido_ticket'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.CharField(max_length=10, primary_key=True, serialize=False, validators=[django.core.validators.MinLengthValidator(10), Gestion.Validadores.validacion_numeros])),
                ('nombre', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), Gestion.Validadores.validar_nombres])),
                ('apellido', models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), Gestion.Validadores.validar_nombres])),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=15, validators=[Gestion.Validadores.validar_telefono])),
                ('email', models.EmailField(max_length=254, unique=True)),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'db_table': 'Cliente',
            },
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(choices=[('1', 'Alimentos'), ('2', 'Bebidas'), ('3', 'Ropa')], max_length=50),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='apellido',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), Gestion.Validadores.validar_nombres], verbose_name='Apellidos'),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='nombre',
            field=models.CharField(max_length=50, validators=[django.core.validators.MaxLengthValidator(50), Gestion.Validadores.validar_nombres]),
        ),
        migrations.AlterField(
            model_name='empleado',
            name='telefono',
            field=models.CharField(max_length=50, validators=[Gestion.Validadores.validacion_numeros]),
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('codigo', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('stock', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(100)])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='Gestion.categoria')),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'db_table': 'Producto',
            },
        ),
        migrations.DeleteModel(
            name='Ticket',
        ),
    ]
